pipeline {
    agent any

    tools {
        jdk 'jdk17'    // Ensure this matches the JDK version installed in Jenkins
        maven 'maven3' // Ensure this matches the Maven version installed in Jenkins
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'  // Ensure 'sonar-scanner' matches the SonarScanner tool name in Jenkins
        DOCKER_IMAGE = 'username/myapp:1.0'  // Define your Docker image repository and tag
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/username/repo-name.git'
            }
        }


        stage('Code Compile') {
            steps {
                sh "mvn clean compile"
            }
        }


        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh 'mvn sonar:sonar'
                }
            }
        }


        stage('Code Build') {
            steps {
                sh "mvn package -DskipTests=true"
            }
        }


        stage('Docker Image Build & Scan') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE -f docker/Dockerfile ."
                    sh "trivy image --format table -o trivy-image-report.html $DOCKER_IMAGE"
                }
            }
        }


        stage('Docker Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh "docker push $DOCKER_IMAGE"
                    }
                }
            }
        }
    }


    post {
        always {
            cleanWs()  // Clean up workspace after build
        }
    }
}
