vm_name: centos7-vm
box: generic/centos7              # from Vagrant Cloud - often faster
hostname: centos.local
private_ip: 192.168.56.20

forwarded_port:
  guest: 80
  host: 8080

public_network: false           # or true

memory: 1024
cpus: 1
gui: false
