vms:
  - name: web
    box: ubuntu/focal64         # Ubuntu 20.04 LTS
    hostname: web.local
    ip: 192.168.56.10
    provision:
      type: shell
      path: provision/web.sh

  - name: db
    box: rockylinux/8               # Rocky Linux 8 RHEL-compatible, community-driven
    hostname: db.local
    ip: 192.168.56.11
    provision:
      type: shell
      path: provision/db.sh
